<?php
/**
 * @author Mikhail Kulakovskiy <m@klkvsk.ru>
 * @date 2016-10-08
 */

namespace OnPhp\Services\Codegen\Typescript;

use \OnPhp\Services\Codegen\AbstractSourceCodeBuilder;
use \OnPhp\Services\Codegen\SourceCodeClassReference;
use \OnPhp\Services\Codegen\SourceCodeTypeReference;
use \OnPhp\Services\Meta\MetaProperty;

abstract class AbstractTypescriptSourceCodeBuilder extends AbstractSourceCodeBuilder
{
    /**
     * @param $value
     * @return $this
     * @throws \WrongArgumentException
     */
    public function addValue($value)
    {
        if (is_array($value)) {
            $this->addArray(
                $value,
                array_keys($value) != range(0, count($value) - 1), // is assoc
                count($value) > 4 // max values until multiline
            );
        } else if ($value instanceof SourceCodeClassReference) {
            $value = TypescriptSourceCodeClassReference::wrap($value);
            $this->add($value->getSelfName());

        } else if ($value instanceof TypescriptSourceCodeTypeReference) {
            $this->add($value->toString());

        } else if (is_string($value)) {
            $this->addString($value);

        } else if (is_bool($value)) {
            $this->add($value ? 'true' : 'false');

        } else if (is_null($value)) {
            $this->add('null');

        } else if (is_numeric($value)) {
            $this->add($value);

        } else {
            throw new \WrongArgumentException('wtf should i do with it?');
        }
        return $this;
    }

    protected function addString($string)
    {
        return $this->add('\'' . addslashes($string) . '\'');
    }

    protected function addArray(array $array, $assoc = false, $multiline = false)
    {
        $this->add($assoc ? '{' : '[');
        if ($multiline) {
            $this->indent()->newLine();
        }
        $length = count($array);
        $num = 0;
        foreach ($array as $key => $value) {
            $num++;
            if ($assoc) {
                $this->addString($key)->add(': ');
            }
            $this->addValue($value);
            if ($num < $length) {
                $this->add(', ');
            }
            if ($multiline) {
                $this->newLine();
            }
        }
        if ($multiline) {
            $this->unindent()->newLine();
        }
        $this->add($assoc ? '}' : ']');

        return $this;
    }

    /**
     * @param $className
     * @return TypescriptSourceCodeClassReference
     */
    public function classRef($className)
    {
        if ($className instanceof SourceCodeClassReference) {
            return TypescriptSourceCodeClassReference::wrap($className);
        } else {
            return TypescriptSourceCodeClassReference::create($className);
        }
    }

    /**
     * @param $type
     * @return TypescriptSourceCodeTypeReference
     */
    public function typeRef($type)
    {
        if ($type instanceof SourceCodeTypeReference) {
            return TypescriptSourceCodeTypeReference::wrap($type);
        } else {
            return TypescriptSourceCodeTypeReference::create($type);
        }
    }

    public function build()
    {
        $this
            ->clean()
            ->addHeaderDocForAutogenerated()
            ->newLine();
    }

    public function addPrimitiveDefinition(MetaProperty $property)
    {
        $type = $this->typeRef($property->getType());
        $primitiveName = $type->getPrimitiveName();
        $primitive = call_user_func([\Primitive::class, $primitiveName], $property->getName());
        $this
            ->add($this->classRef(\Primitive::class)->getStatic($type->getPrimitiveName()))
            //->addArguments([$property->getName()])
            ->indent()
            ->newLine();

        // set additional params
        if ($primitive instanceof \ComplexPrimitive) {
            $this->addLine('->setSingle()');
        }
        if ($primitive instanceof \PrimitiveForm) {
            $this->addLine('->ofProto(' . $this->classRef($type->getTypeName())->getStatic('entityProto()') . ')');
        }
        if ($primitive instanceof \IdentifiablePrimitive) {
            $this->addLine('->of(' . $this->classRef($type->getTypeName())->getSelfName() . ')');
        }
        // required or optional
        if ($property->isRequired()) {
            $this->add('.setRequired(')->addValue($property->isRequired())->add(')')->newLine();
        }

        // convert to ArrayOfPrimitive if it is array
        if ($type->isArray()) {
            $this->addLine('.arrayOf()');
        }

        $this->unindent();
        return $this;
    }

}